-- MySQL Script generated by MySQL Workbench
-- Mon Jan 20 14:47:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`clientes` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NULL,
  `direccion` VARCHAR(60) NOT NULL,
  `codigo_postal` VARCHAR(15) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`tiendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`tiendas` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`tiendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(80) NOT NULL,
  `codigo_postal` VARCHAR(15) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`empleados` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`empleados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `nif` VARCHAR(15) NOT NULL,
  `tipo_empleado` ENUM("repartidor", "cocinero") NOT NULL,
  `id_tienda` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_empleado_tienda`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `pizzeria`.`tiendas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_empleado_tienda_idx` ON `pizzeria`.`empleados` (`id_tienda` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pizzeria`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hora_fecha` DATETIME NOT NULL,
  `tipo_pedido` ENUM("domicilio", "recogida") NOT NULL,
  `precio_total` FLOAT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_tienda` INT NOT NULL,
  `id_repartidor` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `pizzeria`.`clientes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_tienda`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `pizzeria`.`tiendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_repartidor`
    FOREIGN KEY (`id_repartidor`)
    REFERENCES `pizzeria`.`empleados` (`id`)
    ON DELETE CASCADE
    ON UPDATE SET NULL)
ENGINE = InnoDB;

CREATE INDEX `fk_pedido_cliente_idx` ON `pizzeria`.`pedidos` (`id_cliente` ASC) VISIBLE;

CREATE INDEX `fk_pedido_tienda_idx` ON `pizzeria`.`pedidos` (`id_tienda` ASC) VISIBLE;

CREATE INDEX `fk_pedido_repartidor_idx` ON `pizzeria`.`pedidos` (`id_repartidor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pizzeria`.`categoria_pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`categoria_pizza` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`categoria_pizza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`productos` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo_producto` ENUM("Hamburguesa", "Pizza", "Bebida") NOT NULL,
  `descripcion` MEDIUMTEXT NULL,
  `imagen` VARCHAR(255) NULL,
  `precio` FLOAT NOT NULL,
  `id_categoria_pizza` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_categoria_pizzas`
    FOREIGN KEY (`id_categoria_pizza`)
    REFERENCES `pizzeria`.`categoria_pizza` (`id`)
    ON DELETE CASCADE
    ON UPDATE SET NULL)
ENGINE = InnoDB;

CREATE INDEX `fk_categoria_pizzas_idx` ON `pizzeria`.`productos` (`id_categoria_pizza` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pizzeria`.`productos_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`productos_pedido` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`productos_pedido` (
  `id_pedido` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad_producto` INT NOT NULL,
  CONSTRAINT `fk_id_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `pizzeria`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `pizzeria`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_id_producto_idx` ON `pizzeria`.`productos_pedido` (`id_producto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
